# Script version for the docker-compose.yml file.
version: '3'
services:
    ### API Containter ###
    api:
        # MongoDB image name/version.
        image: sheldonpi1999/intelliflow-api:1.2

        # Defines that the service "mongo" must be running before this api service initializes.
        depends_on: ['mongo']

        # This defines the ports through which the service will be available.
        ports:
            - "3030:3030"
  
    ### MongoDB Containter ###
    mongo:
        # MongoDB image name/version.
        image: mongo:4.4.5

        # Container always restarts if an error occured.
        restart: always
        
        # This defines the name of the container.
        container_name: mongodb

        # Folder where the data is stored as files.
        volumes:
            - ./db/mongodb:/db/mongodb
        
        # This defines the service internal port and the host port.
        ports: 
            - "27017:27017"

        # Basic login 
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    ### BROKER Containter ###
    broker:
        # MongoDB image name/version.
        image: sheldonpi1999/intelliflow-broker:1.2

        # Defines that the service "mongo" must be running before this api service initializes.
        depends_on: ['api']

        # This defines the ports through which the service will be available.
        ports:
            - "1883:1883"
  
    ### RethinkDB Containter ###
    rethink:
        # RethinkDB image name/version.
        image: djtidau/rethinkdb-2.4.1

        # Container always restarts if an error occured.
        restart: always
        
        # This defines the name of the container.
        container_name: rethinkdb

        # Folder where the data is stored as files.
        volumes:
            - ./db/rethinkdb:/db/rethinkdb
        
        # This defines the service internal port and the host port.
        ports: 
            - 28015:28015
            - 8081:8081