name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        with: 
          path: "./packages/testd/"
        id: package-version
 
      - name: Build testd
        run: | 
          docker build packages/testd --file packages/testd/Dockerfile -t docker.pkg.github.com/pxldigital/3eai-pem-2021-data-pixel/datapixel.testd:${{ steps.package-version.outputs.version }}

      - name: docker push
        run: |
          docker push docker.pkg.github.com/pxldigital/3eai-pem-2021-data-pixel/datapixel.testd:${{ steps.package-version.outputs.version }}
